import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { AuroraBackground } from "@/components/ui/aurora-background";

const inter = Inter();
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased bg-slate-50 dark:bg-zinc-900`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AuroraBackground>
            {children}
          </AuroraBackground>
        </ThemeProvider>
      </body>
    </html>
  );
}
